/*
 * File: app/store/TestStore.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MediLab.store.TestStore', {
    extend: 'Ext.data.Store',
    alias: 'store.TestStore',
    requires: [
        'MediLab.model.TestModel'
    ],

    config: {
        autoLoad: true,
        model: 'MediLab.model.TestModel',
        storeId: 'testStore',
        proxy: {
            type: 'ajax',
            url: 'data/test.json',
            reader: {
                type: 'json',
                rootProperty: 'tests'
            }
        },
        grouper: {
            groupFn: function(record) {
                return record.get('name')[0];
            }
        }
    }
});