/*
 * File: app/store/TestTemp.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MediLab.store.TestTemp', {
    extend: 'Ext.data.Store',
    alias: 'store.testtemp',
    requires: [
        'MediLab.model.TestTempModel'
    ],

    config: {
        autoLoad: true,
        data: [
            {
                test: 'A Test'
            },
            {
                test: 'B1 Test'
            },
            {
                test: 'B2 Test'
            },
            {
                test: 'C1 Test'
            },
            {
                test: 'C2 Test'
            },
            {
                test: 'C3 Test'
            },
            {
                test: 'D Test'
            },
            {
                test: 'E Test'
            }
        ],
        model: 'MediLab.model.TestTempModel',
        storeId: 'testTemp',
        grouper: {
            groupFn: function(record) {
                return record.get('test')[0];
            },
            sortProperty: 'test'
        }
    }
});