/*
 * File: app/view/LoginFormPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MediLab.view.LoginFormPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.loginformpanel',

    config: {
        id: 'loginFormPanel',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'MediLab Touch'
            },
            {
                xtype: 'fieldset',
                id: 'LoginFieldSet',
                width: '100%',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'loginUserName',
                        label: '',
                        placeHolder: 'User name'
                    },
                    {
                        xtype: 'textfield',
                        id: 'loginPassword',
                        placeHolder: 'Password'
                    },
                    {
                        xtype: 'button',
                        id: 'loginButton',
                        text: 'Login'
                    }
                ]
            },
            {
                xtype: 'list',
                height: 233,
                id: 'loginMenuList',
                ui: 'round',
                width: '100%',
                scrollable: false,
                itemTpl: [
                    '<div>{option}</div>'
                ],
                store: 'loginMenuArrayStore',
                allowDeselect: true,
                onItemDisclosure: true
            }
        ]
    }

});