/*
 * File: app/view/PhysicianNavView.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MediLab.view.PhysicianNavView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.physiciannavview',
    requires: [
        'MediLab.view.TestByNameList',
        'MediLab.view.TestSearchByList',
        'MediLab.view.PhysicianMenuContainer'
    ],

    config: {
        items: [
            {
                xtype: 'testbynamelist',
                title: 'Tests by name'
            },
            {
                xtype: 'testsearchbylist',
                title: 'Test portfolio search'
            },
            {
                xtype: 'physicianmenucontainer',
                title: 'Physician'
            }
        ]
    }

});