/*
 * File: app/view/PhysicianMenu.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MediLab.view.PhysicianMenu', {
    extend: 'Ext.Panel',
    alias: 'widget.physicianmenu',

    config: {
        items: [
            {
                xtype: 'list',
                height: 400,
                id: '',
                ui: 'round',
                width: '100%',
                itemTpl: [
                    '<div>{option}</div>'
                ],
                store: 'physicianMenuArrayStore',
                allowDeselect: true,
                onItemDisclosure: true,
                name: 'PhysicianMenuList'
            }
        ]
    }

});