/*
 * File: app/view/PickerTest.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MediLab.view.PickerTest', {
    extend: 'Ext.Container',
    alias: 'widget.pickerTest',

    config: {
        items: [
            {
                xtype: 'button',
                itemId: 'mybutton2',
                text: 'Pick a specialty'
            }
        ],
        listeners: [
            {
                fn: 'onMybutton2Tap',
                event: 'tap',
                delegate: '#mybutton2'
            }
        ]
    },

    onMybutton2Tap: function(button, e, options) {
        var picker = button.numberPicker;

        if (!picker) {
            picker = button.specialtiesPicker = Ext.Viewport.add({
                xtype: 'specialtiespicker',
                listeners: {
                    change: function(picker, values) {
                        var s1 = values.specialty;
                        'Specialty Selected', 
                        'You chose the specialty ' + s1 + '.'
                    }
                }
            });
        }

        picker.setValue({
            specialty: 1
        });

        picker.show();
    }

});