/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'PhysicianMenuModel',
        'LoginMenuModel',
        'TestModel',
        'TestMenuModel',
        'SpecialtyModel',
        'ConditionModel'
    ],
    stores: [
        'LoginMenuArrayStore',
        'PhysicianMenuArrayStore',
        'TestMenuArrayStore',
        'TestStore',
        'SpecialtyStore',
        'ConditionStore'
    ],
    views: [
        'PhysicianTabPanel',
        'Account',
        'Contact',
        'Help',
        'LoginFormPanel',
        'TestsByKeyword',
        'PhysicianNavView',
        'TestDetail',
        'TestSearch',
        'TestsBySpecialty',
        'PendingOrders',
        'PatientList',
        'NewOrder',
        'TestsByCondition',
        'PhysicianMenu',
        'TestsByName'
    ],
    name: 'MediLab',
    controllers: [
        'LoginFormController',
        'PhysicianMenu',
        'TestSearch',
        'TestByName',
        'TestsByKeyWord',
        'TestsBySpecialty',
        'TestsByCondition'
    ],

    launch: function() {

        Ext.Viewport.add({
            xclass: 'MediLab.view.LoginFormPanel'
            //xclass: 'MediLab.view.TestByNameList'
            //xclass: 'MediLab.view.ByKeywordList'
            //xclass: 'MediLab.view.PickerTest'

            // xclass: 'MediLab.view.BySpecialty'
            //xclass: 'MediLab.view.TestsByName'



        });



    },

    showViewByPush: function(callerDataView, navigationView, xtypeToShow, title) {
        console.log (xtypeToShow + "  view pushed by itemtap event handler ");

        callerDataView.up(navigationView).push({
            xtype : xtypeToShow,
            title : title
        });
    }

});
