/*
 * File: app/controller/PhysicianMenu.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MediLab.controller.PhysicianMenu', {
    extend: 'Ext.app.Controller',
    alias: 'controller.physicianmenu',
    config: {
        refs: {
            physicianmenu: '#physicianmenu',
            physiciannavview: '#physiciannavview'
        },

        control: {
            "physicianmenu [name=PhysicianMenuList]": {
                itemtap: 'onListItemTap'
            },
            "button": {
                tap: 'onButtonTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, options) {
        //alert("The Physician Menu list has been disclosed");




        switch(index) {
            case 0:


            var navigationView = 'physiciannavview',
                xtypeToShow = 'patientlist',
                title = 'Patient List';

            MediLab.app.showViewByPush(dataview, navigationView, xtypeToShow, title);




            break;

            case 1:

            var navigationView = 'physiciannavview',
                xtypeToShow = 'neworder',
                title = 'New Order';

            MediLab.app.showViewByPush(dataview, navigationView, xtypeToShow, title);



            break;

            case 2:

            var navigationView = 'physiciannavview',
                xtypeToShow = 'pendingorders',
                title = 'Physician Pending orders';

            MediLab.app.showViewByPush(dataview, navigationView, xtypeToShow, title);


            break;

            case 3:

            var navigationView = 'physiciannavview',
                xtypeToShow = 'testsearch',
                title = 'Test Search Menu';

            MediLab.app.showViewByPush(dataview, navigationView, xtypeToShow, title);

            break;

            case 4:

            console.log ("LoginFormPanel view pushed by itemtap event handler " + index);
            Ext.Viewport.setActiveItem({xtype: 'loginformpanel'});
        }

    },

    onButtonTap: function(button, e, options) {
        /*
        button.up('physiciannavview').push({
        xtype:'testsearchpanel',
        title: 'Test Search'
        });
        */
    }

});