/*
 * File: app/controller/PhysicianMenuController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MediLab.controller.PhysicianMenuController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.physicianmenucontroller',
    config: {
        refs: {
            physicianmenulist: 'physicianmenulist',
            physiciannavview: '#physicianNavView'
        },

        control: {
            "#physicianMenuList": {
                disclose: 'onPhysicianMenuListDisclosure'
            },
            "navigationview": {
                activate: 'onNavigationviewActivate'
            },
            "button": {
                tap: 'onButtonTap'
            }
        }
    },

    onPhysicianMenuListDisclosure: function(list, record, target, index, e, options) {
        //alert("The Physician Menu list has been disclosed");
        switch(index) {
            case 0:
            Ext.Viewport.setActiveItem({xtype: 'mypatientslist'});
            break;

            case 1:
            Ext.Viewport.setActiveItem({xtype: 'neworderslist'});
            break;

            case 2:
            Ext.Viewport.setActiveItem({xtype: 'pendingorderslist'});
            break;

            //This is not the correct way to push the testsearchbylist view, we need to understand how to navigate correctly Navigation views in order to move forward.
            case 3:

            //Ext.Viewport.setActiveItem({xtype: 'pendingorderslist'});

            //var a=Ext.getCmp("physicianNavView"), b=Ext.getCmp("physicianMenu"); 
            //var physicianNavView =Ext.getCmp("physiciannavniew"), testSearchPanel=Ext.getCmp("testsearchpanel"); 

            //console.log("valor de physicianNavView: ", physicianNavView); 
            //console.log("valor de testSearchPanel: ", testSearchPanel); 
            //physicianNavView.push(testSearchPanel);


            //Ext.ComponentManager.get('physicianNavView').push('testSearchByList');
            //Ext.Viewport.setActiveItem({xtype: 'testsearchbylist'});



            var currentView = Ext.ComponentQuery.query('physiciannavview');
            console.log("valor de currentView: ", currentView);       
            currentView.push({
                xtype:'testsearchpanel',
                title: 'Test Search'
            });



            break;

            case 4:
            Ext.Viewport.setActiveItem({xtype: 'loginformpanel'});

        }

    },

    onNavigationviewActivate: function(container, newActiveItem, oldActiveItem, options) {
        console.log('Container value', container);
        //alert(oldActiveItem);

        var a=Ext.getCmp("testSearchByList"), b=Ext.getCmp("physicianNavView"); 

        console.log("valor de testSearchByList: ", a); 
        console.log("valor de physicianNavView: ", b); 

        if (oldActiveItem === undefined) {
            //alert ("esta indefinido");
            b.setActiveItem(0);
        } else {
            //alert ("Voy de: "+oldActiveItem + " Voy para: " + newActiveItem);
            b.setActiveItem(newActiveItem);
        }




    },

    onButtonTap: function(button, e, options) {

        button.up('physiciannavview').push({
            xtype:'testsearchpanel',
            title: 'Test Search'
        });
    }

});