/*
 * File: app/controller/TestsByCondition.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MediLab.controller.TestsByCondition', {
    extend: 'Ext.app.Controller',
    config: {
        refs: {
            testsbycondition: '#testsbycondition'
        },

        control: {
            "testsbycondition [name=conditionPicker]": {
                change: 'onSelectfieldChange'
            },
            "testsbycondition [name=TestsByConditionList]": {
                itemtap: 'onListItemTap'
            }
        }
    },

    onSelectfieldChange: function(selectfield, newValue, oldValue, options) {

        // Set and get the stores needed for the process
        conditionStore=Ext.getStore('conditionStore');
        testStore=Ext.getStore('testStore');

        console.log("conditionStore", conditionStore);
        console.log("testStore", testStore);

        // Get the picked index in the view
        idx = conditionStore.findBy(function (record) {
            console.log("Procesing inside findBy: record.data.name:", record.data.name);
            return record.data.id == newValue;
        });

        //Clear all filters on the testStore
        testStore.clearFilter(true);

        // Gets the specialty name
        name=conditionStore.getAt(idx).data.name;
        console.log("-------------------------------------------");
        console.log("Condition Selected:", name);

        // Filters the Test store to get only the records mached with the condition selected.
        // Use the function for each record in the store and return only records needed
        testStore.clearFilter(true);
        testStore.filter(function (record) {

            var arr = record.data.condition, continuar = false;
            console.log("Test Name:", record.data.name);
            for(var i=0; i<arr.length; i++) {
                console.log(" >> Condition proc:", arr[i].name);
                if (arr[i].name == name) {
                    continuar = true;
                }
            }
            return continuar;
        }

        );


    },

    onListItemTap: function(dataview, index, target, record, e, options) {
        console.log("The Test Detail item tap:", record.data.name );

        dataview.up('physiciannavview').push({
            xtype : 'testdetail',
            title : 'Test Detail',
            data: record.getData()
        });

    }

});