/*
 * File: app/controller/TestSearch.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MediLab.controller.TestSearch', {
    extend: 'Ext.app.Controller',
    alias: 'controller.testsearch',
    config: {
        refs: {
            testsearch: 'testsearch'
        },

        control: {
            "testsearch [id=testSearchPanelOptions]": {
                itemtap: 'onListItemTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, options) {
        //alert("The Test Portfolio list has been disclosed");
        switch(index) {
            case 0:
            //Ext.Viewport.setActiveItem({xtype: 'testbynamelist'});

            console.log ("TestsByName view pushed by itemtap event handler " + index);

            Ext.getStore('testStore').load();
            dataview.up('physiciannavview').push({
                xtype : 'testsbyname',
                title : 'Tests By Name'
            });



            break;

            case 1:
            // Ext.Viewport.setActiveItem({xtype: 'bykeywordlist'});

            console.log ("TestsByKeyword view pushed by itemtap event handler " + index);

            dataview.up('physiciannavview').push({
                xtype : 'testsbykeyword',
                title : 'Tests By Keyword'
            });


            break;

            case 2:


            console.log ("TestsBySpecialty view pushed by itemtap event handler " + index);

            dataview.up('physiciannavview').push({
                xtype : 'testsbyspecialty',
                title : 'Tests By Specialty'
            });



            break;

            case 3:


            console.log ("TestsByCondition view pushed by itemtap event handler " + index);

            dataview.up('physiciannavview').push({
                xtype : 'testsbycondition',
                title : 'Tests By Condition'
            });
            break;   

            case 4:
            // Ext.Viewport.setActiveItem({xtype: 'bydiseaselist'});


            console.log ("TestsByDisease view pushed by itemtap event handler " + index);

            dataview.up('physiciannavview').push({
                xtype : 'testsbydisease',
                title : 'Tests By Disease'
            });


        }


    }

});