/*
 * File: app/controller/TestMenuController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MediLab.controller.TestMenuController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.testmenucontroller',
    config: {
        refs: {
            testportfolioview: 'testportfolioview'
        },

        control: {
            "#testMenuList": {
                disclose: 'onTestMenuListDisclosure'
            }
        }
    },

    onTestMenuListDisclosure: function(list, record, target, index, e, options) {
        //alert("The Test Portfolio list has been disclosed");
        switch(index) {
            case 0:
            Ext.Viewport.setActiveItem({xtype: 'testportfolioview'});
            break;

            case 1:
            Ext.Viewport.setActiveItem({xtype: 'bykeywordlist'});
            break;

            case 2:
            Ext.Viewport.setActiveItem({xtype: 'byspecialtylist'});
            break;

            case 3:
            Ext.Viewport.setActiveItem({xtype: 'byconditionlist'});
            break;

            case 4:
            Ext.Viewport.setActiveItem({xtype: 'bydiseaselist'});

        }
    }

});