/*
 * File: app/controller/TestsBySpecialty.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MediLab.controller.TestsBySpecialty', {
    extend: 'Ext.app.Controller',
    config: {
        control: {
            "testsbyspecialty [name=specialtyPicker]": {
                change: 'onSelectfieldChange'
            },
            "testsbyspecialty [name=TestsBySpecialtyList]": {
                itemtap: 'onListItemTap'
            }
        }
    },

    onSelectfieldChange: function(selectfield, newValue, oldValue, options) {


        // Set and get the stores needed for the process
        specialtyStore=Ext.getStore('specialtyStore');
        testStore=Ext.getStore('testStore');

        console.log("specialtyStore", specialtyStore);
        console.log("testStore", testStore);

        // Get the specialty index picked in the view
        specialtyIdx = specialtyStore.findBy(function (record) {
            console.log("Procesing insed findBy: record.data.name:", record.data.name);
            return record.data.id == newValue;
        });

        //Clear all filters on the testStore
        testStore.clearFilter(true);

        // Gets the specialty name
        specialtyName=specialtyStore.getAt(specialtyIdx).data.name;
        console.log("-------------------------------------------");
        console.log("Specialty Selected:", specialtyName);

        // Filters the Test store to get only the records mached with the specialty selected.
        // Use the function for each record in the store and return only records needed
        testStore.clearFilter(true);
        testStore.filter(function (record) {

            var arr = record.data.specialty, continuar = false;
            console.log("Test Name:", record.data.name);
            for(var i=0; i<arr.length; i++) {
                console.log(" >> Specialty proc:", arr[i].name);
                if (arr[i].name == specialtyName) {
                    continuar = true;
                }
            }
            return continuar;
        }

        );



    },

    onListItemTap: function(dataview, index, target, record, e, options) {
        console.log("The Test Detail item tap:", record.data.name );

        dataview.up('physiciannavview').push({
            xtype : 'testdetail',
            title : 'Test Detail',
            data: record.getData()
        });

    }

});