/*
 * File: app/controller/TestByName.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MediLab.controller.TestByName', {
    extend: 'Ext.app.Controller',
    config: {
        refs: {
            testbynamelist: '#testbynamelist'
        },

        control: {
            "testsbyname [name=TestsByNameList]": {
                itemtap: 'onListItemTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, options) {
        console.log("The Test Detail item tap:", record.data.name );

        dataview.up('physiciannavview').push({
            xtype : 'testdetail',
            title : 'Test Detail',
            data: record.getData()
        });


    }

});